### ISSUE TITLE
Encrypt passwords before persisting in Database

### ISSUE THREAD

**Issue by jerrydevin96** [Colris-Inc/auth#1]
Passwords need to be encrypted with AES encryption, before saving in DB. An appropriate decrypt function also needs to be developed to decrypt the encrypted password.

**Comment by rajkumarGosavi** [comment]
Hi,
I am interested in working on this issue

**Comment by jerrydevin96** [comment]
Hi Rajkumar,
Thanks for taking interest in this issue.
I have created a package called as encryption in the code base and you will find 2 functions inside without the actual implementation.

The code base is not mature yet (just letting you know). To understand the application you can refer to the high level design in the wiki section.

You can fork the repo and raise a pull request later with your implementation.

Hope this helps :) 

Please let me know if you need more info

**Comment by rajkumarGosavi** [comment]
https://github.com/Colris-Inc/auth/pull/2
Please review
